export type DiscoverCategory =
  | 'all'
  | 'politics'
  | 'philosophy'
  | 'science'
  | 'literature'
  | 'psychology'
  | 'arts'
  | 'nature'

export interface DiscoverWord {
  word: string
  pos: string
  snippet: string
  category: Exclude<DiscoverCategory, 'all'>
}

export const CATEGORY_LABELS: Record<DiscoverCategory, string> = {
  all: 'All',
  politics: '🏛 Politics',
  philosophy: '🧠 Philosophy',
  science: '🔬 Science',
  literature: '📚 Literature',
  psychology: '🧪 Psychology',
  arts: '🎨 Arts',
  nature: '🌿 Nature',
}

export const DISCOVER_WORDS: DiscoverWord[] = [
  // ── General / cross-category ──────────────────────────────────────────
  { word: 'sanguine',       pos: 'adjective', snippet: 'Optimistic, especially in a difficult situation.',                        category: 'psychology' },
  { word: 'laconic',        pos: 'adjective', snippet: 'Using very few words; brief and to the point.',                          category: 'literature' },
  { word: 'equanimity',     pos: 'noun',      snippet: 'Calmness and composure, especially in difficulty.',                      category: 'psychology' },
  { word: 'audacious',      pos: 'adjective', snippet: 'Showing bold disregard for normal restraints.',                          category: 'arts' },
  { word: 'alacrity',       pos: 'noun',      snippet: 'Brisk and cheerful readiness.',                                          category: 'psychology' },
  { word: 'tenacious',      pos: 'adjective', snippet: 'Determined; not giving up easily.',                                      category: 'psychology' },
  { word: 'eloquent',       pos: 'adjective', snippet: 'Fluent and persuasive in speaking or writing.',                          category: 'literature' },
  { word: 'loquacious',     pos: 'adjective', snippet: 'Tending to talk a great deal; garrulous.',                               category: 'literature' },
  { word: 'perspicacious',  pos: 'adjective', snippet: 'Having a ready insight; shrewd.',                                        category: 'philosophy' },
  { word: 'brevity',        pos: 'noun',      snippet: 'Concise and exact use of words in writing or speech.',                   category: 'literature' },
  { word: 'enigmatic',      pos: 'adjective', snippet: 'Difficult to interpret or understand; mysterious.',                      category: 'arts' },
  { word: 'euphoria',       pos: 'noun',      snippet: 'A feeling of intense happiness or excitement.',                          category: 'psychology' },
  { word: 'candour',        pos: 'noun',      snippet: 'The quality of being open and honest in expression.',                    category: 'philosophy' },
  { word: 'pensive',        pos: 'adjective', snippet: 'Engaged in or reflecting deep, serious thought.',                       category: 'literature' },
  { word: 'acrimony',       pos: 'noun',      snippet: 'Bitterness or ill feeling, especially in speech or manner.',            category: 'politics' },
  { word: 'intrepid',       pos: 'adjective', snippet: 'Fearless and adventurous; boldly courageous.',                          category: 'literature' },
  { word: 'ruminate',       pos: 'verb',      snippet: 'To think deeply and at length about something.',                        category: 'psychology' },
  { word: 'panache',        pos: 'noun',      snippet: 'A confident, flamboyant, and stylish manner.',                          category: 'arts' },
  { word: 'reticent',       pos: 'adjective', snippet: 'Not revealing one\'s thoughts or feelings readily.',                    category: 'psychology' },
  { word: 'insidious',      pos: 'adjective', snippet: 'Proceeding in a gradual, subtle, but harmful way.',                     category: 'politics' },
  { word: 'sagacious',      pos: 'adjective', snippet: 'Having or showing keen mental discernment and good judgment.',          category: 'philosophy' },
  { word: 'torpor',         pos: 'noun',      snippet: 'A state of physical or mental inactivity; lethargy.',                   category: 'psychology' },
  { word: 'ameliorate',     pos: 'verb',      snippet: 'To make something bad or unsatisfactory better.',                       category: 'politics' },
  { word: 'lassitude',      pos: 'noun',      snippet: 'Physical or mental weariness; lack of energy.',                         category: 'psychology' },
  { word: 'obfuscate',      pos: 'verb',      snippet: 'To render obscure, unclear, or unintelligible.',                        category: 'politics' },
  { word: 'vacillate',      pos: 'verb',      snippet: 'To waver between different opinions or actions; be indecisive.',        category: 'psychology' },
  { word: 'fastidious',     pos: 'adjective', snippet: 'Very attentive to and concerned about accuracy and detail.',            category: 'arts' },
  { word: 'querulous',      pos: 'adjective', snippet: 'Complaining in a petulant or whining manner.',                          category: 'literature' },
  { word: 'magnanimous',    pos: 'adjective', snippet: 'Very generous or forgiving, especially toward a rival or someone less powerful.', category: 'politics' },
  { word: 'vicissitude',    pos: 'noun',      snippet: 'A change of circumstances or fortune, especially an unwelcome one.',   category: 'philosophy' },
  { word: 'corroborate',    pos: 'verb',      snippet: 'To confirm or give support to a statement, theory, or finding.',       category: 'science' },
  { word: 'penultimate',    pos: 'adjective', snippet: 'Last but one in a series of things; second to last.',                  category: 'literature' },
  { word: 'obstreperous',   pos: 'adjective', snippet: 'Noisy and difficult to control; unruly.',                               category: 'politics' },
  { word: 'propitious',     pos: 'adjective', snippet: 'Giving or indicating a good chance of success; favourable.',           category: 'literature' },
  { word: 'verisimilitude', pos: 'noun',      snippet: 'The appearance of being true or real; believability.',                  category: 'literature' },
  { word: 'soliloquy',      pos: 'noun',      snippet: 'An act of speaking thoughts aloud when alone or regardless of hearers.', category: 'literature' },

  // ── Politics & Law ────────────────────────────────────────────────────
  { word: 'suffrage',       pos: 'noun',      snippet: 'The right to vote in political elections.',                              category: 'politics' },
  { word: 'gerrymandering', pos: 'noun',      snippet: 'Manipulating electoral boundaries to favour a particular party.',       category: 'politics' },
  { word: 'filibuster',     pos: 'noun',      snippet: 'A prolonged speech obstructing legislative progress.',                  category: 'politics' },
  { word: 'hegemony',       pos: 'noun',      snippet: 'Leadership or dominance, especially of one country or group over others.', category: 'politics' },
  { word: 'jurisprudence',  pos: 'noun',      snippet: 'The theory or philosophy of law.',                                      category: 'politics' },
  { word: 'oligarchy',      pos: 'noun',      snippet: 'A small group of people having control of a country or organisation.',  category: 'politics' },
  { word: 'manifesto',      pos: 'noun',      snippet: 'A public declaration of policy and aims, especially by a political party.', category: 'politics' },
  { word: 'sedition',       pos: 'noun',      snippet: 'Conduct or speech inciting rebellion against the authority of a state.', category: 'politics' },
  { word: 'demagogue',      pos: 'noun',      snippet: 'A political leader who seeks support through prejudice and false claims.', category: 'politics' },
  { word: 'plebiscite',     pos: 'noun',      snippet: 'A direct vote of all members of an electorate on an important question.', category: 'politics' },
  { word: 'autocracy',      pos: 'noun',      snippet: 'A system of government by one person with absolute power.',             category: 'politics' },
  { word: 'polity',         pos: 'noun',      snippet: 'A form of government or political organisation of a nation or state.',  category: 'politics' },
  { word: 'sovereignty',    pos: 'noun',      snippet: 'Supreme power, especially over a body politic; authority of a state.',  category: 'politics' },
  { word: 'promulgate',     pos: 'verb',      snippet: 'To make a law or decree known to the public; put into effect officially.', category: 'politics' },
  { word: 'adjudicate',     pos: 'verb',      snippet: 'To make a formal judgment or decision about a disputed matter.',       category: 'politics' },
  { word: 'bicameral',      pos: 'adjective', snippet: 'Having two legislative chambers, such as the Senate and House.',       category: 'politics' },
  { word: 'enfranchise',    pos: 'verb',      snippet: 'To give the right to vote to; grant freedom to.',                      category: 'politics' },
  { word: 'recuse',         pos: 'verb',      snippet: 'To withdraw from a case due to a conflict of interest.',               category: 'politics' },
  { word: 'impeach',        pos: 'verb',      snippet: 'To charge a public official with misconduct in office.',               category: 'politics' },
  { word: 'redress',        pos: 'noun',      snippet: 'Remedy or compensation for a wrong or grievance.',                     category: 'politics' },

  // ── Philosophy ────────────────────────────────────────────────────────
  { word: 'epistemology',   pos: 'noun',      snippet: 'The branch of philosophy concerned with the nature and scope of knowledge.', category: 'philosophy' },
  { word: 'dialectic',      pos: 'noun',      snippet: 'The art of investigating truth through logical discussion.',            category: 'philosophy' },
  { word: 'sophistry',      pos: 'noun',      snippet: 'The use of clever but false arguments to deceive.',                    category: 'philosophy' },
  { word: 'solipsism',      pos: 'noun',      snippet: 'The view that the self is all that can be known to exist.',            category: 'philosophy' },
  { word: 'teleology',      pos: 'noun',      snippet: 'The explanation of phenomena in terms of the purpose they serve.',    category: 'philosophy' },
  { word: 'nihilism',       pos: 'noun',      snippet: 'The rejection of all religious and moral principles; belief in nothing.', category: 'philosophy' },
  { word: 'phenomenology',  pos: 'noun',      snippet: 'The study of structures of experience and consciousness.',             category: 'philosophy' },
  { word: 'heuristic',      pos: 'adjective', snippet: 'Enabling discovery through investigation rather than set rules.',      category: 'philosophy' },
  { word: 'tautology',      pos: 'noun',      snippet: 'A statement that is true by necessity or by virtue of its logical form.', category: 'philosophy' },
  { word: 'syllogism',      pos: 'noun',      snippet: 'A form of reasoning in which a conclusion follows from two premises.',  category: 'philosophy' },
  { word: 'cogitate',       pos: 'verb',      snippet: 'To think deeply about something; meditate or reflect.',               category: 'philosophy' },
  { word: 'zeitgeist',      pos: 'noun',      snippet: 'The defining spirit or mood of a particular period in history.',      category: 'philosophy' },
  { word: 'dogma',          pos: 'noun',      snippet: 'A principle or set of principles held by an authority as incontrovertibly true.', category: 'philosophy' },
  { word: 'paradigm',       pos: 'noun',      snippet: 'A typical example or pattern of something; a model or framework.',    category: 'philosophy' },
  { word: 'axiomatic',      pos: 'adjective', snippet: 'Self-evidently true; taken for granted as an established truth.',     category: 'philosophy' },
  { word: 'ontology',       pos: 'noun',      snippet: 'The branch of metaphysics dealing with the nature of being and existence.', category: 'philosophy' },
  { word: 'empiricism',     pos: 'noun',      snippet: 'The theory that knowledge comes only from sensory experience.',       category: 'philosophy' },
  { word: 'quandary',       pos: 'noun',      snippet: 'A state of perplexity or uncertainty about what to do.',              category: 'philosophy' },
  { word: 'stoicism',       pos: 'noun',      snippet: 'Enduring pain or hardship without showing feelings or complaint.',    category: 'philosophy' },
  { word: 'heresy',         pos: 'noun',      snippet: 'An opinion contrary to accepted doctrine or dominant belief.',        category: 'philosophy' },

  // ── Science ───────────────────────────────────────────────────────────
  { word: 'entropy',        pos: 'noun',      snippet: 'A measure of disorder or randomness in a system; gradual decline.',   category: 'science' },
  { word: 'catalyst',       pos: 'noun',      snippet: 'Something that precipitates or speeds up an event or change.',        category: 'science' },
  { word: 'synthesis',      pos: 'noun',      snippet: 'The combination of elements to form a connected whole.',              category: 'science' },
  { word: 'taxonomy',       pos: 'noun',      snippet: 'The classification of things into ordered categories.',               category: 'science' },
  { word: 'anomaly',        pos: 'noun',      snippet: 'Something that deviates from what is standard or expected.',          category: 'science' },
  { word: 'parsimony',      pos: 'noun',      snippet: 'The quality of using the simplest assumption; extreme frugality.',   category: 'science' },
  { word: 'bifurcation',    pos: 'noun',      snippet: 'The division of something into two branches or parts.',              category: 'science' },
  { word: 'stochastic',     pos: 'adjective', snippet: 'Randomly determined; having a probability distribution.',            category: 'science' },
  { word: 'extrapolate',    pos: 'verb',      snippet: 'To extend findings beyond known data by inference or estimation.',   category: 'science' },
  { word: 'postulate',      pos: 'verb',      snippet: 'To suggest or assume as a basis for reasoning without proof.',       category: 'science' },
  { word: 'osmosis',        pos: 'noun',      snippet: 'The process by which molecules pass through a membrane; gradual absorption.', category: 'science' },
  { word: 'empirical',      pos: 'adjective', snippet: 'Based on observation or experiment rather than theory or logic.',    category: 'science' },
  { word: 'iterate',        pos: 'verb',      snippet: 'To perform or utter repeatedly; to repeat a process to generate outcomes.', category: 'science' },
  { word: 'inertia',        pos: 'noun',      snippet: 'Resistance to change; tendency to remain in the current state.',    category: 'science' },
  { word: 'fission',        pos: 'noun',      snippet: 'The splitting of a nucleus; division of a cell or organism.',        category: 'science' },
  { word: 'exponential',    pos: 'adjective', snippet: 'Increasingly rapid; characterised by a constant rate of growth.',   category: 'science' },
  { word: 'hypothesis',     pos: 'noun',      snippet: 'A proposed explanation made on the basis of limited evidence.',     category: 'science' },
  { word: 'osmotic',        pos: 'adjective', snippet: 'Of or relating to osmosis; involving gradual absorption.',          category: 'science' },
  { word: 'quantum',        pos: 'noun',      snippet: 'The minimum amount of any physical entity involved in an interaction.', category: 'science' },
  { word: 'corollary',      pos: 'noun',      snippet: 'A natural consequence; a result that follows from an established fact.', category: 'science' },

  // ── Literature ────────────────────────────────────────────────────────
  { word: 'allegory',       pos: 'noun',      snippet: 'A story with a hidden meaning, often moral or political.',           category: 'literature' },
  { word: 'denouement',     pos: 'noun',      snippet: 'The final resolution of a story\'s plot.',                           category: 'literature' },
  { word: 'leitmotif',      pos: 'noun',      snippet: 'A recurring theme associated with a particular idea or character.',  category: 'literature' },
  { word: 'hubris',         pos: 'noun',      snippet: 'Excessive pride or self-confidence, often leading to downfall.',    category: 'literature' },
  { word: 'pathos',         pos: 'noun',      snippet: 'A quality that evokes pity or sadness; an appeal to emotion.',      category: 'literature' },
  { word: 'bathos',         pos: 'noun',      snippet: 'An abrupt, jarring transition from the elevated to the trivial.',   category: 'literature' },
  { word: 'anachronism',    pos: 'noun',      snippet: 'A thing belonging to a period other than that in which it exists.', category: 'literature' },
  { word: 'elegy',          pos: 'noun',      snippet: 'A poem of serious reflection, typically a lament for the dead.',   category: 'literature' },
  { word: 'didactic',       pos: 'adjective', snippet: 'Intended to teach, particularly with moral instruction.',           category: 'literature' },
  { word: 'catharsis',      pos: 'noun',      snippet: 'The process of releasing strong or repressed emotions.',            category: 'literature' },
  { word: 'vignette',       pos: 'noun',      snippet: 'A brief, evocative description or episode in a story.',            category: 'literature' },
  { word: 'allusion',       pos: 'noun',      snippet: 'An indirect reference to something, especially in literature.',    category: 'literature' },
  { word: 'satire',         pos: 'noun',      snippet: 'The use of humour and irony to expose and criticise folly.',       category: 'literature' },
  { word: 'hyperbole',      pos: 'noun',      snippet: 'Exaggerated statements not meant to be taken literally.',           category: 'literature' },
  { word: 'juxtaposition',  pos: 'noun',      snippet: 'Placing two contrasting things close together for effect.',        category: 'literature' },
  { word: 'subtext',        pos: 'noun',      snippet: 'An underlying theme or meaning not explicitly stated.',             category: 'literature' },
  { word: 'anecdote',       pos: 'noun',      snippet: 'A short, personal story used to illustrate a point.',              category: 'literature' },
  { word: 'rhetoric',       pos: 'noun',      snippet: 'Language designed to have a persuasive or impressive effect.',    category: 'literature' },
  { word: 'prose',          pos: 'noun',      snippet: 'Written language in its ordinary form, without metrical structure.',category: 'literature' },
  { word: 'motif',          pos: 'noun',      snippet: 'A distinctive feature or dominant idea in an artistic work.',      category: 'literature' },

  // ── Psychology ────────────────────────────────────────────────────────
  { word: 'projection',     pos: 'noun',      snippet: 'Unconsciously attributing one\'s own feelings to another person.',  category: 'psychology' },
  { word: 'transference',   pos: 'noun',      snippet: 'Redirecting feelings about one person onto another.',               category: 'psychology' },
  { word: 'narcissism',     pos: 'noun',      snippet: 'Excessive interest in oneself and one\'s physical appearance.',    category: 'psychology' },
  { word: 'sublimation',    pos: 'noun',      snippet: 'Channelling unacceptable impulses into socially acceptable outlets.',category: 'psychology' },
  { word: 'gaslighting',    pos: 'noun',      snippet: 'Manipulating someone into questioning their own perception or sanity.', category: 'psychology' },
  { word: 'ambivalence',    pos: 'noun',      snippet: 'Simultaneously holding contradictory feelings about something.',   category: 'psychology' },
  { word: 'dissociation',   pos: 'noun',      snippet: 'A disconnection between thoughts, identity, and surroundings.',    category: 'psychology' },
  { word: 'neuroplasticity',pos: 'noun',      snippet: 'The brain\'s ability to reorganise itself by forming new connections.', category: 'psychology' },
  { word: 'archetype',      pos: 'noun',      snippet: 'A universally recognised symbol or pattern of behaviour.',         category: 'psychology' },
  { word: 'rapport',        pos: 'noun',      snippet: 'A close and harmonious relationship with easy communication.',    category: 'psychology' },
  { word: 'schema',         pos: 'noun',      snippet: 'A cognitive framework that helps organise and interpret information.', category: 'psychology' },
  { word: 'intrinsic',      pos: 'adjective', snippet: 'Belonging naturally; coming from within, not from external rewards.',category: 'psychology' },
  { word: 'cognitive',      pos: 'adjective', snippet: 'Relating to conscious mental activities such as thinking and reasoning.', category: 'psychology' },
  { word: 'resilience',     pos: 'noun',      snippet: 'The capacity to recover quickly from difficulties; toughness.',   category: 'psychology' },
  { word: 'cathartic',      pos: 'adjective', snippet: 'Providing psychological relief through expressing strong emotion.', category: 'psychology' },
  { word: 'compulsion',     pos: 'noun',      snippet: 'An irresistible urge to behave in a certain way, against one\'s will.', category: 'psychology' },
  { word: 'empathy',        pos: 'noun',      snippet: 'The ability to understand and share the feelings of another.',     category: 'psychology' },
  { word: 'fixation',       pos: 'noun',      snippet: 'An obsessive attachment to a particular person, thing, or idea.',  category: 'psychology' },
  { word: 'altruism',       pos: 'noun',      snippet: 'Selfless concern for the well-being of others.',                   category: 'psychology' },
  { word: 'ennui',          pos: 'noun',      snippet: 'A feeling of listlessness and dissatisfaction arising from boredom.', category: 'psychology' },

  // ── Arts & Culture ────────────────────────────────────────────────────
  { word: 'baroque',        pos: 'adjective', snippet: 'Highly ornate and extravagant in style; elaborate and richly detailed.', category: 'arts' },
  { word: 'avant-garde',    pos: 'adjective', snippet: 'New and experimental ideas and methods in art or culture.',        category: 'arts' },
  { word: 'pastiche',       pos: 'noun',      snippet: 'A work imitating the style of another artist or era.',            category: 'arts' },
  { word: 'mimesis',        pos: 'noun',      snippet: 'The imitative representation of nature in art and literature.',   category: 'arts' },
  { word: 'iconography',    pos: 'noun',      snippet: 'The visual images and symbols associated with a subject or work.',category: 'arts' },
  { word: 'chiaroscuro',    pos: 'noun',      snippet: 'The contrast of light and shade in drawings and paintings.',      category: 'arts' },
  { word: 'gestalt',        pos: 'noun',      snippet: 'Something perceived as a whole that is more than the sum of its parts.', category: 'arts' },
  { word: 'kitsch',         pos: 'noun',      snippet: 'Art, objects, or design considered garish or lacking in taste.',  category: 'arts' },
  { word: 'sublime',        pos: 'adjective', snippet: 'Of such excellence or beauty as to inspire great admiration.',    category: 'arts' },
  { word: 'semiotics',      pos: 'noun',      snippet: 'The study of signs and symbols and their interpretation.',        category: 'arts' },
  { word: 'vernacular',     pos: 'noun',      snippet: 'The language or dialect of a particular group or region.',        category: 'arts' },
  { word: 'opus',           pos: 'noun',      snippet: 'A musical composition numbered as one of a composer\'s works.',   category: 'arts' },
  { word: 'oeuvre',         pos: 'noun',      snippet: 'The complete body of work of a painter, composer, or author.',   category: 'arts' },
  { word: 'aesthetic',      pos: 'adjective', snippet: 'Concerned with beauty or the appreciation of beauty.',            category: 'arts' },
  { word: 'evocative',      pos: 'adjective', snippet: 'Bringing strong images, memories, or feelings to mind.',         category: 'arts' },
  { word: 'impresario',     pos: 'noun',      snippet: 'A person who organises and finances operas, concerts, or plays.', category: 'arts' },
  { word: 'ethereal',       pos: 'adjective', snippet: 'Extremely delicate and light; heavenly or spiritual.',            category: 'arts' },
  { word: 'virtuoso',       pos: 'noun',      snippet: 'A person with outstanding skill in a musical or artistic pursuit.', category: 'arts' },
  { word: 'melancholy',     pos: 'noun',      snippet: 'A feeling of pensive sadness, typically without obvious cause.',  category: 'arts' },
  { word: 'cadence',        pos: 'noun',      snippet: 'A rhythmic sequence; the rise and fall of the voice in speaking.', category: 'arts' },

  // ── Nature ────────────────────────────────────────────────────────────
  { word: 'endemic',        pos: 'adjective', snippet: 'Native to and restricted to a particular region or habitat.',     category: 'nature' },
  { word: 'symbiosis',      pos: 'noun',      snippet: 'A mutually beneficial relationship between two different organisms.', category: 'nature' },
  { word: 'fecund',         pos: 'adjective', snippet: 'Producing or capable of producing an abundance of offspring.',   category: 'nature' },
  { word: 'sylvan',         pos: 'adjective', snippet: 'Relating to or characteristic of woods and forests.',            category: 'nature' },
  { word: 'ephemeral',      pos: 'adjective', snippet: 'Lasting for a very short time; transitory.',                     category: 'nature' },
  { word: 'primordial',     pos: 'adjective', snippet: 'Existing at or from the beginning of time; primeval.',           category: 'nature' },
  { word: 'verdant',        pos: 'adjective', snippet: 'Green with grass or other rich vegetation; lush.',               category: 'nature' },
  { word: 'riparian',       pos: 'adjective', snippet: 'Relating to or situated on the banks of a river.',              category: 'nature' },
  { word: 'diurnal',        pos: 'adjective', snippet: 'Active during the day; of or during daytime.',                   category: 'nature' },
  { word: 'nocturnal',      pos: 'adjective', snippet: 'Done, occurring, or active at night.',                           category: 'nature' },
  { word: 'littoral',       pos: 'adjective', snippet: 'Of or relating to the shore of the sea or a lake.',             category: 'nature' },
  { word: 'arboreal',       pos: 'adjective', snippet: 'Living in or relating to trees.',                                category: 'nature' },
  { word: 'perennial',      pos: 'adjective', snippet: 'Lasting or existing for a long or apparently infinite time.',    category: 'nature' },
  { word: 'estival',        pos: 'adjective', snippet: 'Belonging to or appearing in summer.',                           category: 'nature' },
  { word: 'petrichor',      pos: 'noun',      snippet: 'The pleasant smell that frequently accompanies rain on dry earth.',category: 'nature' },
  { word: 'sibilant',       pos: 'adjective', snippet: 'Making or characterised by a hissing sound.',                   category: 'nature' },
  { word: 'quiescent',      pos: 'adjective', snippet: 'In a state of quiet inactivity; dormant.',                       category: 'nature' },
  { word: 'boreal',         pos: 'adjective', snippet: 'Relating to the north; of the northern forest zone.',           category: 'nature' },
  { word: 'salient',        pos: 'adjective', snippet: 'Most noticeable or important; projecting outward.',              category: 'nature' },
  { word: 'lambent',        pos: 'adjective', snippet: 'Softly bright; glowing; playing lightly over a surface.',       category: 'nature' },
]
